production:
  line:
    channel_id: <%= ENV["LINE_CHANNEL_ID"] %>
    channel_secret: <%= ENV["LINE_CHANNEL_SECRET"] %>
    channel_mid: <%= ENV["LINE_CHANNEL_MID"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
development:
  secret_key_base: 'hoge'
  redis_url: 'redis://localhost:6347'
